# Generated by Django 2.1.1 on 2018-09-19 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='début')),
            ],
            options={
                'verbose_name': 'liste',
                'verbose_name_plural': 'listes',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ListedProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='canal.List')),
            ],
            options={
                'verbose_name': 'listed program',
                'verbose_name_plural': 'listed programs',
                'ordering': ('list', 'order'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='identifiant de la vidéo')),
                ('yt_etag', models.CharField(max_length=255, verbose_name='Etag Youtube')),
                ('yt_title', models.CharField(max_length=100, verbose_name='titre Youtube')),
                ('yt_description', models.TextField(max_length=5000, verbose_name='description Youtube')),
                ('duration', models.DurationField(verbose_name='durée')),
            ],
            options={
                'verbose_name': 'vidéo',
                'verbose_name_plural': 'vidéos',
            },
        ),
        migrations.AddField(
            model_name='listedprogram',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='canal.Video'),
        ),
        migrations.AddField(
            model_name='list',
            name='videos',
            field=models.ManyToManyField(through='canal.ListedProgram', to='canal.Video', verbose_name='vidéos'),
        ),
    ]
