# Generated by Django 2.1.1 on 2018-09-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('start_date', models.DateTimeField(verbose_name='Starting time')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='Video ID')),
                ('yt_title', models.CharField(max_length=100, verbose_name='Youtube title')),
                ('duration', models.DurationField(verbose_name='Duration')),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='videos',
            field=models.ManyToManyField(to='canal.Video'),
        ),
    ]
