# Generated by Django 2.1.1 on 2018-09-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='yt_description',
            field=models.TextField(default='', max_length=5000, verbose_name='Youtube description'),
            preserve_default=False,
        ),
    ]
