# Generated by Django 2.1.1 on 2018-09-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listedprogram',
            options={'ordering': ('list', 'order'), 'verbose_name': 'programme', 'verbose_name_plural': 'programmes'},
        ),
        migrations.AddField(
            model_name='video',
            name='yt_thumbnail',
            field=models.URLField(default='', verbose_name='Youtube thumbnail'),
            preserve_default=False,
        ),
    ]
