# Generated by Django 2.1.1 on 2018-09-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canal', '0002_video_yt_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='yt_etag',
            field=models.CharField(default='', max_length=255, verbose_name='Youtube etag'),
            preserve_default=False,
        ),
    ]
